/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AppSideDrawer {
    'open': () => void;
    'opened': boolean;
    'title': string;
  }
  interface AppSideDrawerAttributes extends StencilHTMLAttributes {
    'opened'?: boolean;
    'title'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppSideDrawer': Components.AppSideDrawer;
  }

  interface StencilIntrinsicElements {
    'app-side-drawer': Components.AppSideDrawerAttributes;
  }


  interface HTMLAppSideDrawerElement extends Components.AppSideDrawer, HTMLStencilElement {}
  var HTMLAppSideDrawerElement: {
    prototype: HTMLAppSideDrawerElement;
    new (): HTMLAppSideDrawerElement;
  };

  interface HTMLElementTagNameMap {
    'app-side-drawer': HTMLAppSideDrawerElement
  }

  interface ElementTagNameMap {
    'app-side-drawer': HTMLAppSideDrawerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
